### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Stealth2800** [FlexSeries/FlexChat#5]
NPE occurring when a chatter (not in the town channel) attempts to join a channel + instance combination.

```
[01:12:45] [Server thread/ERROR]: [FlexChat] §cAn error occurred while running this command ({MESSAGE}).
java.lang.NullPointerException
        at me.st28.flexseries.flexchat.commands.channel.CmdChannel.handleExecute(CmdChannel.java:81) ~[FlexChat.jar:2.0.1-SNAPSHOT]
        at me.st28.flexseries.flexlib.command.AbstractCommand.execute(AbstractCommand.java:275) ~[FlexLib.jar:0.0.0-SNAPSHOT]
        at me.st28.flexseries.flexlib.command.FlexCommandWrapper.onCommand(FlexCommandWrapper.java:80) [FlexLib.jar:0.0.0-SNAPSHOT]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by Stealth2800** [comment]
Haven't seen this occur again. Closing.
