### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Stealth2800** [FlexSeries/FlexChat#8]
Unsure of what circumstances were.

```
[23:35:35] [Async Chat Thread - #94/ERROR]: Could not pass event ChannelChatEvent to FlexChat v2.0.1-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at me.st28.flexseries.flexchat.backend.ChatManager.onAsyncPlayerChatHighest(ChatManager.java:145) [FlexChat.jar:2.0.1-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1087) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1025) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Chatter cannot be null.
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        at me.st28.flexseries.flexchat.api.channel.ChannelInstance.containsChatter(ChannelInstance.java:128) ~[?:?]
        at me.st28.flexseries.flexchat.backend.chatadmin.ChatAdminManager.onChannelChat(ChatAdminManager.java:205) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor440.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[paperspigot.jar:git-PaperSpigot-978982e-12698ea]
        ... 19 more
```

**Comment by Stealth2800** [comment]
Haven't seen this come up again. Closing.
